In [1]:
import numpy as np

In [26]:
arr = np.array([1,2,3,4,0],dtype='i')
arr, arr.dtype

(array([1, 2, 3, 4, 0], dtype=int32), dtype('int32'))

In [20]:
arr = np.array(['11','22','33',''], dtype='bool')
arr, arr.dtype

(array([ True,  True,  True, False]), dtype('bool'))

In [27]:
arr

array([1, 2, 3, 4, 0], dtype=int32)

In [28]:
arr.astype('f')

array([1., 2., 3., 4., 0.], dtype=float32)

In [79]:
arr = np.linspace(1, 100, 1000)
arr

array([  1.        ,   1.0990991 ,   1.1981982 ,   1.2972973 ,
         1.3963964 ,   1.4954955 ,   1.59459459,   1.69369369,
         1.79279279,   1.89189189,   1.99099099,   2.09009009,
         2.18918919,   2.28828829,   2.38738739,   2.48648649,
         2.58558559,   2.68468468,   2.78378378,   2.88288288,
         2.98198198,   3.08108108,   3.18018018,   3.27927928,
         3.37837838,   3.47747748,   3.57657658,   3.67567568,
         3.77477477,   3.87387387,   3.97297297,   4.07207207,
         4.17117117,   4.27027027,   4.36936937,   4.46846847,
         4.56756757,   4.66666667,   4.76576577,   4.86486486,
         4.96396396,   5.06306306,   5.16216216,   5.26126126,
         5.36036036,   5.45945946,   5.55855856,   5.65765766,
         5.75675676,   5.85585586,   5.95495495,   6.05405405,
         6.15315315,   6.25225225,   6.35135135,   6.45045045,
         6.54954955,   6.64864865,   6.74774775,   6.84684685,
         6.94594595,   7.04504505,   7.14414414,   7.24

In [80]:
arr.astype('i')

array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,
         2,   2,   2,   2,   2,   2,   2,   2,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   4,   4,   4,   4,   4,   4,   4,   4,
         4,   4,   5,   5,   5,   5,   5,   5,   5,   5,   5,   5,   6,
         6,   6,   6,   6,   6,   6,   6,   6,   6,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   9,   9,   9,   9,   9,   9,   9,   9,   9,   9,
        10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  11,  11,  11,
        11,  11,  11,  11,  11,  11,  11,  12,  12,  12,  12,  12,  12,
        12,  12,  12,  12,  12,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  14,  14,  14,  14,  14,  14,  14,  14,  14,  14,  15,
        15,  15,  15,  15,  15,  15,  15,  15,  15,  16,  16,  16,  16,
        16,  16,  16,  16,  16,  16,  17,  17,  17,  17,  17,  17,  17,
        17,  17,  17,  18,  18,  18,  18,  18,  18,  18,  18,  1

In [37]:
a = np.array([10,10,10])
a

array([10, 10, 10])

In [38]:
b = a.copy()
b

array([10, 10, 10])

In [41]:
b[0] = 10000
b

array([10000,    10,    10])

In [42]:
a

array([10, 10, 10])

In [43]:
aa = np.array([10,20,30])
print(aa)
bb = aa.view()
print(bb)

[10 20 30]
[10 20 30]


In [44]:
aa[1] = 200
print(aa)
print(bb)

[ 10 200  30]
[ 10 200  30]


In [46]:
print(aa.base)
print(bb.base)

None
[ 10 200  30]


In [47]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

None
[1 2 3 4 5]


In [48]:
# array reshape

arr

In [50]:
arr.size

5

In [51]:
arr.shape

(5,)

(5,) > (col,) >  1d array
(5, 5) > (row, col) > 2d array
(5, 5, 5) > (access, row, col) > 3d array

In [52]:
arr = np.array([1,2,3,4,56,7,8,9])
arr, arr.ndim

(array([ 1,  2,  3,  4, 56,  7,  8,  9]), 1)

In [54]:
newarr = arr.reshape(4, 2)
newarr, newarr.ndim

(array([[ 1,  2],
        [ 3,  4],
        [56,  7],
        [ 8,  9]]),
 2)

In [57]:
newarr3 = arr.reshape(1,8,1)
newarr3

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [56],
        [ 7],
        [ 8],
        [ 9]]])

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
newarr = arr.reshape(3,3,-1)
newarr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [62]:
arr = np.array([[[[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]]])
arr, arr.ndim

(array([[[[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]]]), 5)

In [63]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [75]:
arr = np.array([[[11,22,33],[10,20,30]]])

# print(arr)

for x in arr:
    for d in x:
        for j in d:
            print(j)

11
22
33
10
20
30


In [82]:
arr = np.array([[[11,22,33],[10,20,30]]])

y = np.nditer(arr)

for i in y:
    print(i)

11
22
33
10
20
30


In [81]:
for i in np.nditer(arr):
    print(i)

1.0
1.0990990990990992
1.1981981981981982
1.2972972972972974
1.3963963963963963
1.4954954954954955
1.5945945945945947
1.6936936936936937
1.7927927927927927
1.8918918918918919
1.990990990990991
2.09009009009009
2.1891891891891895
2.288288288288288
2.3873873873873874
2.4864864864864864
2.5855855855855854
2.684684684684685
2.7837837837837838
2.8828828828828827
2.981981981981982
3.081081081081081
3.18018018018018
3.279279279279279
3.3783783783783785
3.4774774774774775
3.5765765765765765
3.675675675675676
3.774774774774775
3.873873873873874
3.972972972972973
4.072072072072072
4.171171171171171
4.27027027027027
4.36936936936937
4.468468468468469
4.5675675675675675
4.666666666666666
4.7657657657657655
4.864864864864865
4.963963963963964
5.063063063063063
5.162162162162162
5.261261261261262
5.36036036036036
5.45945945945946
5.558558558558558
5.657657657657658
5.756756756756757
5.8558558558558556
5.954954954954955
6.054054054054054
6.153153153153153
6.252252252252252
6.351351351351352
6.4504504

In [85]:
for x in np.nditer(arr, flags=['buffered'],  op_dtypes=['U']):
    print(x)

11
22
33
10
20
30


In [86]:
arr

array([[[11, 22, 33],
        [10, 20, 30]]])

In [87]:
for i in np.nditer(arr[0, 0:, 1:2]):
    print(i)

22
20


In [88]:
arr

array([[[11, 22, 33],
        [10, 20, 30]]])

In [95]:
for i,x in np.ndenumerate(arr):
    print(i,x)

(0, 0, 0) 11
(0, 0, 1) 22
(0, 0, 2) 33
(0, 1, 0) 10
(0, 1, 1) 20
(0, 1, 2) 30


In [98]:
arr1=np.array([111,222,333])
arr2=np.array([444,555,666])

arr=np.concatenate((arr1,arr2))
print(arr)

[111 222 333 444 555 666]


In [101]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,6 ], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # columnwise
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

[1 2 3 4 5 6]


In [118]:
newarr=np.array_split(arr,5)
newarr

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [113]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
# print(arr)

newarr=np.split(arr,1,axis=0)
print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]])]


In [119]:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4) # element

print(arr)
print('Location of index:',x)

[1 2 3 4 5 4 4]
Location of index: (array([3, 5, 6], dtype=int64),)


In [120]:
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr, 8.5, side='right') # <<

print(arr)
print('location where element to be inserted',loc)

[5 7 8 9]
location where element to be inserted 3


In [121]:
arr=np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [124]:
arr.argmax()

99

In [ ]:
1d array > (12,) > (col)
2d array > (12, 10) > (row , col)
3d array > (1, 2, 12) > (access, row, col)


In [1]:
import numpy as np

In [2]:
arr = [[[1,2,3], 
        [4,5,6]], 
       
       [[10,20,30], 
        [40,50,60]]]

In [3]:
print(arr)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]


In [4]:
print(arr)
print(type(arr))
print('*'*100)

# One way is 
print('One way is:')
print('arr[1] :',arr[1])
print('arr[0][0] :',arr[0][0])
print('arr[0][0][2] :',arr[0][0][2])

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
****************************************************************************************************
One way is:
arr[1] : [[10, 20, 30], [40, 50, 60]]
arr[0][0] : [1, 2, 3]
arr[0][0][2] : 3


In [16]:
# Another way
print('Another way is:')
print('arr[1] :' ,arr[1])
print('arr[0,0] :' ,arr[0, 0])
print('arr[0,0,2] :' ,arr[0, 0, 2])

Another way is:
arr[1] : [[ 7  8  9]
 [10 11 12]]
arr[0,0] : [1 2 3]
arr[0,0,2] : 3


In [10]:
import numpy as np

# Assuming arr is a NumPy array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Accessing the element at position (0, 0, 2)
result = arr[0, 0, 2]

print(result)


3


In [51]:
arr = np.array([[[1, 2, 3, 4]]], ndmin=2)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[1 2 3 4]]]
number of dimensions : 3


In [46]:
arr

array([[[1, 2, 3, 4]]])

In [47]:
arr[0, 0, 3] = 1000

In [48]:
arr

array([[[   1,    2,    3, 1000]]])

In [53]:
arr.ndim

3

In [59]:
a1 = np.array([[1,2,3,4]])
a2 = np.array([[11,22,33,44]])

In [60]:
a1, a2

(array([[1, 2, 3, 4]]), array([[11, 22, 33, 44]]))

In [69]:
np.dstack((a1,a2))

array([[[ 1, 11],
        [ 2, 22],
        [ 3, 33],
        [ 4, 44]]])

In [70]:
a3

array([[[ 1,  2,  3,  4]],

       [[11, 22, 33, 44]]])

In [97]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [98]:
np.split(arr, 1)

[array([1, 2, 3, 4, 5])]

In [99]:
arr1 = np.array_split(arr,3)
print(arr1)

[array([1, 2]), array([3, 4]), array([5])]


In [101]:
for i in arr1:
    print(i)

[1 2]
[3 4]
[5]


In [102]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [110]:
np.split(arr,2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [111]:
arr=np.array([1,2,3,4,5,4,4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [119]:
np.searchsorted(arr, 5.1, side='left') # >>

7

In [117]:
np.searchsorted(arr, 1.1, side='right') # <<

1

In [121]:
arr

array([1, 2, 3, 4, 5, 4, 4])

In [120]:
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.24.3


In [4]:
lst = [1,2,3,4,5,6,7,8,9]
a = np.array(lst)
print(a, type(a))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [6]:
tup = (1,2,3,4,5,)
b=np.array(tup)
print(b, type(b))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
c = np.zeros((2,2,2),dtype=float)
print(c, type(c))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] <class 'numpy.ndarray'>


In [8]:
c = np.ones((2,2,2),dtype=float)
print(c, type(c))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] <class 'numpy.ndarray'>


In [11]:
c.ndim

3

In [16]:
a=np.array(10)
print(a, a.ndim)

10 0


In [17]:
b =np.array([1,2,3,4])
print(b, b.ndim)

[1 2 3 4] 1


In [29]:
c = np.array([[1,2,3,4],[11,22,33,44],[10,20,30,40]])
print(c, c.ndim)

[[ 1  2  3  4]
 [11 22 33 44]
 [10 20 30 40]] 2


In [97]:
c[0:3, 3:]

array([[ 4],
       [44],
       [40]])

In [19]:
d = np.array([[[1,2,3]],
         [[4,5,6]],
         [[7,8,9]]])
print(d, d.ndim)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]] 3


In [20]:
b[2]

3

In [28]:
c[0:2,3:4]

array([[4],
       [4]])

In [30]:
c

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [10, 20, 30, 40]])

In [34]:
c[1:3,1:2]

array([[22],
       [20]])

In [59]:
arr = [[[1,2,3], 
       [4,5,6]], 
      
      [[10,20,30], 
       [40,50,60]]]

arr = np.array(arr)


array ouput require:
    arr = [[[3], 
            [6]], 
      
           [[30], 
           [60]]]
    

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [98]:
arr[0:2, 0:2, 2:]

array([[[ 3],
        [ 6]],

       [[30],
        [60]]])

In [100]:
arr[0][0][2]

3

In [1]:
import numpy as np

In [5]:
a = np.array(10)
print(a,type(a), a.ndim)

10 <class 'numpy.ndarray'> 0


In [8]:
a

array(10)

In [9]:
a=np.array([10,20,30,40,50])
print(a,type(a), a.ndim)

[10 20 30 40 50] <class 'numpy.ndarray'> 1


In [17]:
a[::2]

array([10, 30, 50])

In [19]:
for i in range(0, len(a), 2):
    print(a[i])

10
30
50


In [21]:
a=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(a,type(a), a.ndim)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]] <class 'numpy.ndarray'> 2


In [22]:
a[::-1]

array([[100, 110, 120],
       [ 70,  80,  90],
       [ 40,  50,  60],
       [ 10,  20,  30]])

In [23]:
a[:,::-1]

array([[ 30,  20,  10],
       [ 60,  50,  40],
       [ 90,  80,  70],
       [120, 110, 100]])

In [24]:
a[::-1,::-1]

array([[120, 110, 100],
       [ 90,  80,  70],
       [ 60,  50,  40],
       [ 30,  20,  10]])

In [25]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [26]:
a[:,1:2]

array([[ 20],
       [ 50],
       [ 80],
       [110]])

In [30]:
a[0:2,0:1]

array([[10],
       [40]])

In [31]:
a[2:,1:]

array([[ 80,  90],
       [110, 120]])

In [27]:
a[0:2,2:]

array([[30],
       [60]])

In [28]:
a[2:,0:1]

array([[ 70],
       [100]])

In [29]:
a[1:3,2:]

array([[60],
       [90]])

In [32]:
a=np.array([[[10,20,30],[40,50,60]],
            [[70,80,90],[100,110,120]],
            [[1,2,3],[4,5,6]],
            [[7,8,9],[11,22,33]]])
print(a,type(a), a.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 11  22  33]]] <class 'numpy.ndarray'> 3


In [33]:
a[2,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a[2,:,1:2]

array([[2],
       [5]])

In [35]:
a

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 11,  22,  33]]])

In [36]:
a[:,:,2:]

array([[[ 30],
        [ 60]],

       [[ 90],
        [120]],

       [[  3],
        [  6]],

       [[  9],
        [ 33]]])

In [37]:
a

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 11,  22,  33]]])

In [38]:
a[0,:,0:1]

array([[10],
       [40]])

In [39]:
a[3,:,2:]

array([[ 9],
       [33]])

In [40]:
a

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 11,  22,  33]]])

In [44]:
a[::-1,::-1,::-1]

array([[[ 33,  22,  11],
        [  9,   8,   7]],

       [[  6,   5,   4],
        [  3,   2,   1]],

       [[120, 110, 100],
        [ 90,  80,  70]],

       [[ 60,  50,  40],
        [ 30,  20,  10]]])

In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([[[10,20,30],[40,50,60]],
            [[70,80,90],[100,110,120]],
            [[1,2,3],[4,5,6]],
            [[7,8,9],[11,22,33]]])
print(a,type(a), a.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 11  22  33]]] <class 'numpy.ndarray'> 3


In [8]:
a[::-1,:-1]

array([[[ 7,  8,  9]],

       [[ 1,  2,  3]],

       [[70, 80, 90]],

       [[10, 20, 30]]])

In [9]:
a.dtype

dtype('int32')

In [12]:
a=np.array([1,2,3,4,'A',1.2,True])
print(a, a.dtype)

['1' '2' '3' '4' 'A' '1.2' 'True'] <U32


In [20]:
a=np.array([1,2,3,4,5],dtype='i')
a

array([1, 2, 3, 4, 5], dtype=int32)

In [21]:
a.astype(float)

array([1., 2., 3., 4., 5.])

In [22]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [23]:
b=a.copy()
print(b, type(b))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [24]:
b[0]=10

In [25]:
b

array([10,  2,  3,  4,  5], dtype=int32)

In [26]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [27]:
c=a.view()

In [28]:
print(c,type(c))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [29]:
c[0]=1000

In [30]:
c

array([1000,    2,    3,    4,    5], dtype=int32)

In [31]:
a

array([1000,    2,    3,    4,    5], dtype=int32)

In [38]:
a = np.array([1,2,3,4,5,6],ndmin=1)
print(a,a.ndim)

[1 2 3 4 5 6] 1


In [42]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
a=arr.reshape(2,2,3)
a.shape
a.size

12

In [49]:
arr = np.array([[11,44,77,88,99,55]])
a1=arr.reshape(6,)
print(a1, a1.shape, a1.ndim)

[11 44 77 88 99 55] (6,) 1


In [51]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
arr.reshape(-1)

[[10 20 30]
 [40 50 60]]


array([10, 20, 30, 40, 50, 60])

In [56]:
for i in arr:
    for j in i:
        print(j)

10
20
30
40
50
60


In [60]:
y=np.nditer(arr)

In [61]:
for i in y:
    print(i)

10
20
30
40
50
60
