## Numerical Python End to End in Detail

### Numpy:

Numpy- is a **Numerical Python**

It is developed by **Travis Oliphant in 2005**

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays


### Why:

Numpy is built using **python,** and most of the part which requires fatser execution is **developed using c or c++**,So it is very fast in execution.

Numpy arrays are called as **ndarray**

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it **stores numpy arrays at one continuous location**

Numpy codes are available at: https://github.com/numpy/numpy

### Installation of Numpy

In [10]:
import numpy as np

In [12]:
print("Numpy Version is:",np.__version__)

Numpy Version is: 1.24.2


In [13]:
# Create a numpy array using list

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*100)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
****************************************************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [14]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimentions of the array

print('Number of dimensions:',arr.ndim)


[1 2 3 4 5 6 7 8 9]
Number of dimensions: 1


In [15]:
# 2. Create numpy array using tuple

tup=(1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [18]:
# Different Dimentional Arrays:

In [17]:
# 1. 0-D array

arr=np.array(9)
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

9
<class 'numpy.ndarray'>
Dimensons of array: 0


In [21]:
# 2. 1-D array

arr=np.array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 1-D array
print('Element present at 4h index:',arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
Element present at 4h index: 45


In [25]:
# 3. 2-D array
# Array having 1-D array as input element are called as 2-D array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 2-D array
print('Element present at 1st index in axis 0:',arr[0,1]) # arr[0][1]

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimensons of array: 2
Element present at 1st index in axis 0: 2


In [26]:
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2


In [28]:
# Access the elements of 2-D array

print(arr)
# dimensions
print("Dimensions: ",arr.ndim)
print('*'*100)

#one way is to write
print('arr[0][3] :',arr[0][3])
print('arr[0] :',arr[0])
print('arr[0][2] :',arr[0][2])

# another way is like
print('arr[1] :',arr[1])
print('arr[3,1] :',arr[3][1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2
****************************************************************************************************
arr[0][3] : 4
arr[0] : [1 2 3 4]
arr[0][2] : 3
arr[1] : [4 5 6 7]
arr[3,1] : 5


In [30]:
# 4. 3-D Array
# array that has 2-D arrays (matrices) as its elemets is called 3D array

ar = [[[1,2,3], [4,5,6]], [[10,20,30], [40,50,60]]]
print(ar)
print(type(ar))
print('*'*100)

arr=np.array(ar)
print(arr)
print(type(arr))
print('*'*100)

print('Dimension of array :',arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
****************************************************************************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
Dimension of array : 3


In [33]:
# access the elements of the 3-D array

print(arr)
print(type(arr))
print('*'*100)

# One way is 
print('One way is:')
print('arr[1] :',arr[1])
print('arr[0][0] :',arr[0][0])
print('arr[0][0][2] :',arr[0][0][2])

print('*'*100)

# Another way
print('Another way is:')
print('arr[1] :',arr[1])
print('arr[0,0] :',arr[0,0])
print('arr[0,0,2] :',arr[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
One way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0][0] : [1 2 3]
arr[0][0][2] : 3
****************************************************************************************************
Another way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0,0] : [1 2 3]
arr[0,0,2] : 3


###### # create an n dimensional array

In [36]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Array Slicing

In [38]:
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])

1
2
3
4


In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Slice
print("Length: ",len(arr))
print(arr[5:9])

# [start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
Length:  9
[6 7 8 9]


In [40]:
print(arr[0:5])

[1 2 3 4 5]


###### Negative Indices

    Negative indices always start from last element of n-d 
    array i.e. -1st index is last element of ndarray.

In [41]:
print(arr)

[1 2 3 4 5 6 7 8 9]


[-9,-8,-7,-6,-5,-4,-3,-2,-1]

In [43]:
print(arr[-1])
print(arr[-5])
print(arr[-9])

9
5
1


In [47]:
print(arr[-9:-5])

[1 2 3 4]


In [48]:
# Step value in slicing a Numpy array
# here step is 2
print(arr)
print(arr[0:9:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [49]:
print(arr[::2])  # ::2 >> 0 to 9 index by step index 2

print(arr[0:6:2]) # 0:6:2 >> 0 to 6 index by step value 2

[1 3 5 7 9]
[1 3 5]


###### Slicing of 2D Array

In [57]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('\n')
print(arr[1,2])

print(arr[1,1:4]) # arr

print(arr[0,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8
[7 8 9]
[2 3 4]


In [59]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
print(arr[0:1,0:3]) # arr[location index from to,element index from to ]

[[1 2 3]]


In [61]:
print(arr[0:2,0:3]) # arr[location index from to, element index from to ]

[[1 2 3]
 [6 7 8]]


In [62]:
print(arr[0:2,2]) 

[3 8]


In [63]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size, arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15 (3, 5)


In [67]:
# 2, 3
# 20,30

print(arr[0:2,1:3]) 

print('\n')

# 20 30 40
# 22 33 44
print(arr[1:3,1:4])

[[ 2  3]
 [20 30]]


[[20 30 40]
 [22 33 44]]


#### Slicing of 3D Array

In [69]:
arr=np.array([[[1,2,3],[5,6,7]],[[11,22,33],[55,66,77]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]
3


In [77]:
arr[0][1][1:3]

array([6, 7])

In [78]:
arr[1][1][1:3]

array([66, 77])