## Numerical Python End to End in Detail

### Numpy:

Numpy- is a **Numerical Python**

It is developed by **Travis Oliphant in 2005**

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays


### Why:

Numpy is built using **python,** and most of the part which requires fatser execution is **developed using c or c++**,So it is very fast in execution.

Numpy arrays are called as **ndarray**

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it **stores numpy arrays at one continuous location**

Numpy codes are available at: https://github.com/numpy/numpy

### Installation of Numpy

In [10]:
import numpy as np

In [12]:
print("Numpy Version is:",np.__version__)

Numpy Version is: 1.24.2


In [13]:
# Create a numpy array using list

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*100)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
****************************************************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [14]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimentions of the array

print('Number of dimensions:',arr.ndim)


[1 2 3 4 5 6 7 8 9]
Number of dimensions: 1


In [15]:
# 2. Create numpy array using tuple

tup=(1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [18]:
# Different Dimentional Arrays:

In [17]:
# 1. 0-D array

arr=np.array(9)
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

9
<class 'numpy.ndarray'>
Dimensons of array: 0


In [21]:
# 2. 1-D array

arr=np.array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 1-D array
print('Element present at 4h index:',arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
Element present at 4h index: 45


In [25]:
# 3. 2-D array
# Array having 1-D array as input element are called as 2-D array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 2-D array
print('Element present at 1st index in axis 0:',arr[0,1]) # arr[0][1]

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimensons of array: 2
Element present at 1st index in axis 0: 2


In [26]:
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2


In [28]:
# Access the elements of 2-D array

print(arr)
# dimensions
print("Dimensions: ",arr.ndim)
print('*'*100)

#one way is to write
print('arr[0][3] :',arr[0][3])
print('arr[0] :',arr[0])
print('arr[0][2] :',arr[0][2])

# another way is like
print('arr[1] :',arr[1])
print('arr[3,1] :',arr[3][1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2
****************************************************************************************************
arr[0][3] : 4
arr[0] : [1 2 3 4]
arr[0][2] : 3
arr[1] : [4 5 6 7]
arr[3,1] : 5


In [30]:
# 4. 3-D Array
# array that has 2-D arrays (matrices) as its elemets is called 3D array

ar = [[[1,2,3], [4,5,6]], [[10,20,30], [40,50,60]]]
print(ar)
print(type(ar))
print('*'*100)

arr=np.array(ar)
print(arr)
print(type(arr))
print('*'*100)

print('Dimension of array :',arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
****************************************************************************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
Dimension of array : 3


In [33]:
# access the elements of the 3-D array

print(arr)
print(type(arr))
print('*'*100)

# One way is 
print('One way is:')
print('arr[1] :',arr[1])
print('arr[0][0] :',arr[0][0])
print('arr[0][0][2] :',arr[0][0][2])

print('*'*100)

# Another way
print('Another way is:')
print('arr[1] :',arr[1])
print('arr[0,0] :',arr[0,0])
print('arr[0,0,2] :',arr[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
One way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0][0] : [1 2 3]
arr[0][0][2] : 3
****************************************************************************************************
Another way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0,0] : [1 2 3]
arr[0,0,2] : 3


###### # create an n dimensional array

In [36]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Array Slicing

In [38]:
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])

1
2
3
4


In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Slice
print("Length: ",len(arr))
print(arr[5:9])

# [start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
Length:  9
[6 7 8 9]


In [40]:
print(arr[0:5])

[1 2 3 4 5]


###### Negative Indices

    Negative indices always start from last element of n-d 
    array i.e. -1st index is last element of ndarray.

In [41]:
print(arr)

[1 2 3 4 5 6 7 8 9]


[-9,-8,-7,-6,-5,-4,-3,-2,-1]

In [43]:
print(arr[-1])
print(arr[-5])
print(arr[-9])

9
5
1


In [47]:
print(arr[-9:-5])

[1 2 3 4]


In [48]:
# Step value in slicing a Numpy array
# here step is 2
print(arr)
print(arr[0:9:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [49]:
print(arr[::2])  # ::2 >> 0 to 9 index by step index 2

print(arr[0:6:2]) # 0:6:2 >> 0 to 6 index by step value 2

[1 3 5 7 9]
[1 3 5]


###### Slicing of 2D Array

In [57]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('\n')
print(arr[1,2])

print(arr[1,1:4]) # arr

print(arr[0,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8
[7 8 9]
[2 3 4]


In [59]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
print(arr[0:1,0:3]) # arr[location index from to,element index from to ]

[[1 2 3]]


In [61]:
print(arr[0:2,0:3]) # arr[location index from to, element index from to ]

[[1 2 3]
 [6 7 8]]


In [62]:
print(arr[0:2,2]) 

[3 8]


In [63]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size, arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15 (3, 5)


In [67]:
# 2, 3
# 20,30

print(arr[0:2,1:3]) 

print('\n')

# 20 30 40
# 22 33 44
print(arr[1:3,1:4])

[[ 2  3]
 [20 30]]


[[20 30 40]
 [22 33 44]]


#### Slicing of 3D Array

In [69]:
arr=np.array([[[1,2,3],[5,6,7]],[[11,22,33],[55,66,77]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]
3


In [77]:
arr[0][1][1:3]

array([6, 7])

In [78]:
arr[1][1][1:3]

array([66, 77])

### Data Types in NumPy

list of all data types in NumPy:
    
        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex float   
        M - datetime
        O - object
        S - string
        m - timedelta
        U - unicode string
        V - fixed chunk of memory for other type (void)

In [79]:
import numpy as np

In [80]:
# dtype

arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [81]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [83]:
# creating arrays with a defined data type

arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [84]:
arr = np.array([1,2,3,4],dtype='i') # int
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [89]:
arr = np.array([1,2,3,4,5,6],dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [88]:
arr = np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float64


In [90]:
# int with 4 bytes

arr=np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

print('*'*100)

arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
****************************************************************************************************
[1 2 3 4]
int32


in python we are not responsible for memory management PVM is responsible for that

In [92]:
# Errors

# arr=np.array(['a','2','3'],dtype='i')
# print(arr) # ValueError: invalid literal for int() with base 10: 'a'

In [93]:
arr=np.array(['1','2','3'],dtype='i')
print(arr)

[1 2 3]


### Data Type Conversion

In [105]:
# float to int

arr = np.array([1.1, 2.2, 3.3, 4.4])
print('old array:',arr)
print('old array data type :',arr.dtype)
print('*'*100)
new_arr = arr.astype('i')
print('new array',new_arr)
print('new array data type :',new_arr.dtype)

old array: [1.1 2.2 3.3 4.4]
old array data type : float64
****************************************************************************************************
new array [1 2 3 4]
new array data type : int32


In [106]:
# int to bool

arr = np.array([1, 2, 3, 4, 0])
print('old array:',arr)
print('old array data type :',arr.dtype)
print('*'*100)
new_arr = arr.astype(bool)
print('new array',new_arr)
print('new array data type :',new_arr.dtype)

old array: [1 2 3 4 0]
old array data type : int32
****************************************************************************************************
new array [ True  True  True  True False]
new array data type : bool


### Difference Between Copy and View

copy : 

    A copy is a new array that has the same data as the original array. Changes made to the copy do not affect the original array, and vice versa
    
    
view :

    A view is a new array that refers to the same data as the original array. Changes made to the view affect the original array, and vice versa.

In [107]:
# copy() : it is going to create new instance for your value

arr=np.array([1, 2, 3, 4, 5])
x = arr.copy() # seperate object required
arr[0]=42 # updated arr o th index

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [108]:
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
print(x)
x[0] = 100
print(x)

print(arr)
#print(x) 

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [112]:
# view() : 

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

# x = arr
x[0] = 200

print(arr)
print(x) 

[200   2   3   4   5]
[200   2   3   4   5]


In [113]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 4

print(a) # Output: [4 2 3]
print(b) # Output: [4 2 3]


[4 2 3]
[4 2 3]


In [118]:
# best concept : how to identify copy or view
# that will possible by using "base" funcion


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

None
[1 2 3 4 5]


### Numpy Array Reshaping

In [133]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(3,4)
print(newarr)

12
(12,)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(3,2,2)
print(newarr)

12
(12,)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [143]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr=arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [150]:
# create a 2D array and then convert it into 1D array

arr = np.array([[11,44,77,88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77 88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [151]:
arr = np.array([[11,44,77],[88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77]
 [88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [152]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape(3,2)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[11 44]
 [77 88]
 [99 55]]
2


In [148]:
# convert 3D array into 1D array
arr = np.array([[[11,44,77,88,99,55]],[[111,441,717,188,919,515]]])
newarr = arr.reshape(12,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)


[[[ 11  44  77  88  99  55]]

 [[111 441 717 188 919 515]]]
3
****************************************************************************************************
[ 11  44  77  88  99  55 111 441 717 188 919 515]
1


In [154]:
arr = np.array([11,44,77,88,99,55,111,441,717,188,919,515])
newarr = arr.reshape(1,3,4)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[ 11  44  77  88  99  55 111 441 717 188 919 515]
1
****************************************************************************************************
[[[ 11  44  77  88]
  [ 99  55 111 441]
  [717 188 919 515]]]
3


In [149]:
# convert 4D array into 1D array

arr = np.array([[[[11,44,77,88,99,55]]]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[[[11 44 77 88 99 55]]]]
4
****************************************************************************************************
[11 44 77 88 99 55]
1


In [157]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape((1,1,3,2))
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[[[11 44]
   [77 88]
   [99 55]]]]
4


### Numpy Array Reshape Flatten unknown Dimensions

###### If user **dont know any one dimension out 3 dimensions** then numpy can obtain it for user. User have mension the **-1** for that dim.

In [166]:
# Unknown Dimension

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### if u want to obtain a 1-D array using N-D array 

In [168]:
# Flattening(reshape/convert in scalar vector) an Array

arr=np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr.shape)

newarr=arr.reshape(-1)

print(newarr.shape)
print(newarr)

[[10 20 30]
 [40 50 60]]
(2, 3)
(6,)
[10 20 30 40 50 60]


### NumPy Array Iterating

Iterating: means that you going through each element of the array

In [169]:
arr =np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [171]:
# iterating on 2-D array 
arr = np.array([[11,22,33],[10,20,30]])

#print(arr)

for x in arr: # x is taking elemets here
    print(x)

[11 22 33]
[10 20 30]


In [174]:
# Iterating on scalar element of 2-D array

arr=np.array([[1, 2, 3],[4, 5, 6]])

for x in arr: # here x is holding list of elements
    for i in x:
        print(i)

1
2
3
4
5
6


In [181]:
# Iterating on scalar element of 3-D array

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
#     print(x,'\n')
    for i in x:
#          print(i,'\n')
         for j in i:
            print(j,'\n')

1 

2 

3 

4 

5 

6 

7 

8 

9 

10 

11 

12 



###### 1. Using nditer()

In [182]:
# Iterating on 3-D array
arr =np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

y = np.nditer(arr)

for x in y:
    print(x)

1
2
3
4
5
6
7
8


In [184]:
arr =np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [191]:
arr=np.array([[1,2,3,4],[88,88,3939,999]])

print(np.nditer(arr))

for i in np.nditer(arr):
    print(i)

1
2
3
4
88
88
3939
999


In [211]:
# Casting array element from one type to other data type

# Numpy can not at the movemet for that we need to go with "flags" para in nditer

arr=np.array([1, 2, 3])

for x in np.nditer(arr,flags=['buffered'],op_dtypes=['float']):
    print("int to float",x)
    
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['U']):
    print(x)
    
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

1.0
2.0
3.0
1
2
3
b'1'
b'2'
b'3'


In [252]:
# Slicing of an numpy array steps in iterations
# 2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[0:, 0:3:2]): # [Array location,index number::,step_size]
    print(x)

1
3
5
7


In [291]:
# 3D Array
# array[start:end:step, start:end:step, start:end:step]

arr=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])

for x in np.nditer(arr[1:,1::,1::3]):
    print(x)

55


In [299]:
# create a 3D numpy array
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# slice the array along the first dimension
for i in np.nditer(array_3d[0:,:,:]):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [303]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# slice the array with a step size of 2 along the first dimension
for i in np.nditer(array_3d[:,::,::2]):
    print(i)

1
3
4
6
7
9
10
12


###### 2. Using ndenumerate()

    Enumeration means mentioning sequence number of somethings one by one
    
    whenever we want to access any location of element in multi dimentional arrays that time we can use "ndenumerate"
    
    this method always return tuple of index and element

In [307]:
arr = np.array([1, 2, 3])

for x in np.ndenumerate(arr):
    print(x)
    
print('*'*100)    

for i,x in np.ndenumerate(arr):
    print("Index :",i,"Value",x)

((0,), 1)
((1,), 2)
((2,), 3)
****************************************************************************************************
Index : (0,) Value 1
Index : (1,) Value 2
Index : (2,) Value 3


In [310]:
# 2D array

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
for i, val in np.ndenumerate(arr):
    print("Index :",i,"Value",val)

[[1 2 3 4]
 [5 6 7 8]]
Index : (0, 0) Value 1
Index : (0, 1) Value 2
Index : (0, 2) Value 3
Index : (0, 3) Value 4
Index : (1, 0) Value 5
Index : (1, 1) Value 6
Index : (1, 2) Value 7
Index : (1, 3) Value 8


In [311]:
# 3D array

arr=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])

print(arr)
for i, val in np.ndenumerate(arr):
    print("Index :",i,"Value",val)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
Index : (0, 0, 0) Value 1
Index : (0, 0, 1) Value 2
Index : (0, 0, 2) Value 3
Index : (0, 0, 3) Value 4
Index : (0, 1, 0) Value 5
Index : (0, 1, 1) Value 6
Index : (0, 1, 2) Value 7
Index : (0, 1, 3) Value 8
Index : (1, 0, 0) Value 10
Index : (1, 0, 1) Value 20
Index : (1, 0, 2) Value 30
Index : (1, 0, 3) Value 40
Index : (1, 1, 0) Value 50
Index : (1, 1, 1) Value 60
Index : (1, 1, 2) Value 70
Index : (1, 1, 3) Value 80


### Joining Array

    While joining array we should remember "both arrays should have same dimentions"

###### 1. using concatenation 

In [312]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [313]:
# Array concatenation using axis option

# axis = 0 : it represents rows (default)
# axis = 1 : it represents columns

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,6 ], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # columnwise
print(arr)

print('*'*100)

arr = np.concatenate((arr1, arr2), axis=0) # rowwise
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
****************************************************************************************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


###### 2. using Stack Functions

         Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [316]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

print('*'*100)

arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
****************************************************************************************************
[[1 2 3]
 [4 5 6]]


> ###### 2.1 using "hstack function()"

In [317]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


> ###### 2.2 using "vstack function()"

In [318]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


> ###### 2.3 using "dstack function()"

In [319]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


In [320]:
arr1 = np.array([[1, 2, 3],[11,22,33]])
arr2 = np.array([[4, 5, 6],[44,55,66]])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[11 44]
  [22 55]
  [33 66]]]


### Splitting Array

    Joining merges multiple arrays into one and splitting breaks one array into multiple.
    
    syntax:
    
    np.array_split(array,no_split)
    np.split(array,no_split)

> ###### 1. using split()

In [325]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

newarr=np.split(arr,3)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
****************************************************************************************************
[1 2]
[3 4]
[5 6]


In [335]:
# using axis

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

newarr=np.split(arr,3,axis=1)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
****************************************************************************************************
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [337]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
#newarr = np.split(arr, 4) # This will raise an Value Error
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


> ###### 2. array_split()

    If no of elements are less than it adjust in last array 
    
    It dones raise error this will adjust the element in array

In [339]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [342]:
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [343]:
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [346]:
newarr = np.array_split(arr,5)
print(newarr)

print('*'*100)

print(newarr[1])

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
****************************************************************************************************
[3]


In [349]:
# splitting on 2-D array

arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [351]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,2,axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [363]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,4,axis=0)

for i in newarr:
    print(i,'\n')

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]] 

[[11 12]] 



In [364]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,2,axis=1)

for i in newarr:
    print(i,'\n')

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]] 

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]] 



In [369]:
# Array splitting on axis
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])

# print(arr)

newarr = np.array_split(arr, 3, axis=1)

print(newarr) 

print('*'*100)
print(arr,'\n')
newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
****************************************************************************************************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


> ###### 3. using hsplit() opposite of hstack()

In [382]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])

print(arr,'\n')
print('hstack() method:\n')
newarr = np.hstack(arr)
print(newarr,'\n')
newarr = np.hsplit(arr, 3)
# print(arr.shape)
print('hsplit() method:\n')
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

hstack() method:

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18] 

hsplit() method:

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays