In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.2'

In [3]:
arr=np.array([1,2,34,5])
print(arr,type(arr))

[ 1  2 34  5] <class 'numpy.ndarray'>


In [6]:
arr[1]

2

In [7]:
arr.ndim

1

In [8]:
tup=(1,2,3,4,5,)
arr=np.array(tup)
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [17]:
arr_0d=np.array(9)
print('0d_array :',arr_0d)
print('shape of array',arr_0d.shape)
print('array dimentions :',arr_0d.ndim)

0d_array : 9
shape of array ()
array dimentions : 0


In [27]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9])
print('1d_array :',arr_1d)
print('shape of array',arr_1d.shape)
print('array dimentions :',arr_1d.ndim)

1d_array : [1 2 3 4 5 6 7 8 9]
shape of array (9,)
array dimentions : 1


In [33]:
arr_2d=np.array([[1,2,3],[11,22,33],[4,44,55],[5,6,7]])
print('2d_array :\n',arr_2d)
print('shape of array',arr_2d.shape)
print('array dimentions :',arr_2d.ndim)

2d_array :
 [[ 1  2  3]
 [11 22 33]
 [ 4 44 55]
 [ 5  6  7]]
shape of array (4, 3)
array dimentions : 2


In [63]:
arr_3d=np.array([[[1,2,11],[3,4,22]],[[5,6,33],[7,8,44]],[[55,66,77],[88,99,100]]])
print('3d_array :\n',arr_3d)
print('shape of array',arr_3d.shape)
print('array dimentions :',arr_3d.ndim)

3d_array :
 [[[  1   2  11]
  [  3   4  22]]

 [[  5   6  33]
  [  7   8  44]]

 [[ 55  66  77]
  [ 88  99 100]]]
shape of array (3, 2, 3)
array dimentions : 3


In [35]:
arr_2d

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 4, 44, 55],
       [ 5,  6,  7]])

In [44]:
arr_2d[3,2]

7

In [40]:
arr_2d[3][2]

7

In [45]:
arr_2d[0:5,1:2]

array([[ 2],
       [22],
       [44],
       [ 6]])

In [60]:
arr_2d

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 4, 44, 55],
       [ 5,  6,  7]])

In [61]:
# i need output 1,22,55,6

print(arr_2d[0][0],arr_2d[1][1],arr_2d[2][2],arr_2d[3][1])

1 22 55 6


In [64]:
arr_3d

array([[[  1,   2,  11],
        [  3,   4,  22]],

       [[  5,   6,  33],
        [  7,   8,  44]],

       [[ 55,  66,  77],
        [ 88,  99, 100]]])

In [65]:
arr_3d[1][1][2]

44

In [66]:
arr_3d[2,0,2]

77

In [87]:
# n dimentional array creation

arr=np.array([1,2,3,4,5],ndmin=32)
arr,arr.ndim


(array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                       3, 4,
                                       5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]),
 32)

In [92]:
arr=np.array([[[[[[1,2]]]]]],ndmin=32)
arr,arr.ndim

(array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]),
 32)

In [94]:
arr_3d,arr_3d.ndim

(array([[[  1,   2,  11],
         [  3,   4,  22]],
 
        [[  5,   6,  33],
         [  7,   8,  44]],
 
        [[ 55,  66,  77],
         [ 88,  99, 100]]]),
 3)

In [119]:
# need answer 2,4 6,8 66,99

arr_3d[0:3,0:,1:2]

array([[[ 2],
        [ 4]],

       [[ 6],
        [ 8]],

       [[66],
        [99]]])

In [122]:
# 1,3 5,7 55,88

arr_3d[0:3,:,0:1] # [group of 2d array, rows, column]

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[55],
        [88]]])

In [120]:
arr_3d[0:3,0:2,2:]

array([[[ 11],
        [ 22]],

       [[ 33],
        [ 44]],

       [[ 77],
        [100]]])

data types in numpy array

    i/int- integer
    bool - boolean
    uint - unsigned integer
    float - float
    complex - complex float   
    string - string  
    M - datetime
    m - timedelta     
    O - object   
    U - unicode string

In [145]:
import datetime as dt
array1=np.array([1.1, 1.2, 1.3, 1.4],dtype='f')
array1,array1.dtype

(array([1.1, 1.2, 1.3, 1.4], dtype=float32), dtype('float32'))

In [153]:
carray=array1.astype('O')
carray

array([1.100000023841858, 1.2000000476837158, 1.2999999523162842,
       1.399999976158142], dtype=object)

In [155]:
a=np.array([1,2,3,4,5])
print('original array :',a)
b=a.copy()
print('copied array :',b)
print('now we will update the original arrray "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)

original array : [1 2 3 4 5]
copied array : [1 2 3 4 5]
now we will update the original arrray "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original : [1 2 3 4 5]


In [156]:
a=np.array([1,2,3,4,5])
print('original array :',a)
b=a.view()
print('copied array :',b)
print('now we will update the original arrray "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)

original array : [1 2 3 4 5]
copied array : [1 2 3 4 5]
now we will update the original arrray "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original : [100   2   3   4   5]


In [159]:
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)
print(arr.base)

None
[1 2 3 4]
None


In [160]:
array=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])
array,array.ndim

(array([[[ 1,  2,  3],
         [11, 22, 33]],
 
        [[ 4,  5,  6],
         [44, 55, 66]]]),
 3)

In [161]:
array=np.array([[[1,2,3],[11,22,33]],
                [[4,5,6],[44,55,66]]],ndmin=5)
array,array.ndim

(array([[[[[ 1,  2,  3],
           [11, 22, 33]],
 
          [[ 4,  5,  6],
           [44, 55, 66]]]]]),
 5)

In [162]:
array=np.array([[[1,2,3],[11,22,33]],
                [[4,5,6],[44,55,66]]],ndmin=2)
array,array.ndim

(array([[[ 1,  2,  3],
         [11, 22, 33]],
 
        [[ 4,  5,  6],
         [44, 55, 66]]]),
 3)

In [165]:
newarray=array.reshape(4,3) # 2d array
newarray,newarray.ndim

(array([[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6],
        [44, 55, 66]]),
 2)

In [169]:
arr=np.array([1,2,3,4,56,7,8,9])
newarr=arr.reshape(-1)
newarr,newarr.shape

(array([ 1,  2,  3,  4, 56,  7,  8,  9]), (8,))

In [170]:
for i in newarray:
    print(i)

[1 2 3]
[11 22 33]
[4 5 6]
[44 55 66]


In [171]:
for i in newarray:
    for j in i:
        print(j)

1
2
3
11
22
33
4
5
6
44
55
66


In [172]:
arr_2d

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 4, 44, 55],
       [ 5,  6,  7]])

In [173]:
# array printing
for i in arr_2d:
    print(i)

[1 2 3]
[11 22 33]
[ 4 44 55]
[5 6 7]


In [174]:
# element printing
for i in arr_2d:
    for j in i:
        print(j)

1
2
3
11
22
33
4
44
55
5
6
7


In [175]:
arr_3d

array([[[  1,   2,  11],
        [  3,   4,  22]],

       [[  5,   6,  33],
        [  7,   8,  44]],

       [[ 55,  66,  77],
        [ 88,  99, 100]]])

In [176]:
for i in arr_3d:
    print(i)

[[ 1  2 11]
 [ 3  4 22]]
[[ 5  6 33]
 [ 7  8 44]]
[[ 55  66  77]
 [ 88  99 100]]


In [177]:
for i in arr_3d:
    for j in i:
        for k in j:
            print(k)

1
2
11
3
4
22
5
6
33
7
8
44
55
66
77
88
99
100


In [182]:
arr=np.nditer([1,2,3])

for i in np.nditer(arr, flags=['buffered'],op_dtypes=float):
    print('int to float',i)

int to float 1.0
int to float 2.0
int to float 3.0


In [189]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

for i in np.nditer(arr[:,0:4:3]):
    print(i)

1
4
5
8


In [190]:
arr=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])

for i in np.nditer(arr[1:,1:,1:2]):
    print(i)

55


In [191]:
for i in np.nditer(arr[:,:,0:1]):
    print(i)

1
11
4
44


In [192]:
arr=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])

for i in np.ndenumerate(arr[1:,1:,1:2]):
    print(i)

((0, 0, 0), 55)


In [193]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

for i in np.ndenumerate(arr):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


In [194]:
arr1=np.array([1,2,3])
arr2=np.array([11,22,33])

newarr=np.concatenate((arr1,arr2),axis=0)
print(newarr)

[ 1  2  3 11 22 33]


In [196]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,6 ], [7, 8]])

newarr=np.concatenate((arr1,arr2),axis=1)
print(newarr)

[[1 2 5 6]
 [3 4 7 8]]


In [197]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([5, 6, 7])

arr = np.dot((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [201]:
arr1 = np.array([[2, 3],[4,8]])
arr2 = np.array([[5, 6],[9,1]])

arr1.dot(arr2)

array([[37, 15],
       [92, 32]])

2 3
4 8

5 6 
9 1


2*5+3*9  2*6+3*1

4*5+8*9  4*6+8*1  



In [211]:
2*5+3*9

37

In [207]:
2*6+3*1

15

In [208]:
4*5+8*9

92

In [209]:
4*6+8*1

32